#:schema node_modules/wrangler/config-schema.json
name = "urban-ai-backend"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "ACCOUNTS_KV"
id = "49ae5cf66cc14eaaa4f63c42a048733a"

[[kv_namespaces]]
binding = "AI_PIPELINE_KV"
id = "145fd95d27444391ae6390b20424267e"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "webdev-hs24-images"

[[r2_buckets]]
binding = "GEOSJON_BUCKET"
bucket_name = "webdev-hs24-geodata"

[[send_email]]
name = "EMAIL_BINDING"
allowed_destination_addresses = ["noahgerber100@gmail.com", "saimaneesh14@gmail.com", "ehomburg@ethz.ch"]

[[d1_databases]]
binding = "DB"
database_name = "webdev-hs24-database"
database_id = "058eeb89-06be-41dd-80a0-32882d43c089"

[ai]
binding = "AI"